### ISSUE TITLE
Can't Upload CSV File

### ISSUE THREAD

**Issue by gardner** [cobudget/cobudget-api#149]
We tried commas and semicolons. There are different errors for both. Please check the logs around `2016-08-15T00:35:10.033039+00:00 app[web.1]:` There are a whole bunch of email addresses in there that I don't want to post to a github issue.

This is what happens with commas:
```
2016-08-15T00:25:31.533461+00:00 app[web.1]:   Parameters: {"csv"=>#<ActionDispatch::Http::UploadedFile:0x007f8c3829a920 @tempfile=#<Tempfile:/tmp/RackMultipart20160815-12-g7witx.csv>, @original_filename="report-2016-08-15T1102.csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"csv\"; filename=\"report-2016-08-15T1102.csv\"\r\nContent-Type: application/vnd.ms-excel\r\n">, "group_id"=>"255"}
2016-08-15T00:25:31.533903+00:00 app[web.1]: Can't verify CSRF token authenticity
2016-08-15T00:25:31.640514+00:00 app[web.1]: Completed 422 Unprocessable Entity in 107ms (Views: 0.4ms | ActiveRecord: 11.0ms)
2016-08-15T00:25:17+00:00 app[heroku-postgres]: source=DATABASE sample#current_transaction=2977832.0 sample#db_size=12632236.0bytes sample#tables=10 sample#active-connections=15 sample#waiting-connections=0 sample#index-cache-hit-rate=1 sample#table-cache-hit-rate=0.99953 sample#load-avg-1m=0 sample#load-avg-5m=0.005 sample#load-avg-15m=0.025 sample#read-iops=0 sample#write-iops=0 sample#memory-total=3786332.0kB sample#memory-free=907720kB sample#memory-cached=2182140.0kB sample#memory-postgres=77792kB
```

**Comment by gardner** [comment]
I emailed the CSV file.

**Comment by kiesia** [comment]
Please send me a copy too.

**Comment by data-doge** [comment]
i have a feeling that `@content_type="application/vnd.ms-excel"` may be the issue

**Comment by data-doge** [comment]
i'm distrustful of microsoft anything lol

**Comment by kiesia** [comment]
Uh, let's refactor this after OS//OS. 

I tried an upload of the first 50 lines and it worked, but took a very long time.

The import spawns over 800 requests that wait a very long time to connect. With the full file I got a lot of 401 Unauthorized on many requests, which is what is causing the problem. I'm not sure why this is happening, but it looks like auth is timing out at a certain point.

![screenshot from 2016-08-17 18-16-24](https://cloud.githubusercontent.com/assets/783612/17744273/42214f54-64a7-11e6-983f-b17cd9913981.png)

**Comment by data-doge** [comment]
i don't actually think there is a bug -- i think this is a user error 

i'm looking back at the logs now and i'm seeing 

```
Aug 14 17:25:31 cobudget-beta-api heroku/router:  at=info method=POST path="/api/v1/memberships/upload_review?group_id=255" host=cobudget-beta-api.herokuapp.com request_id=2b2fab02-3ed8-4aaa-b79d-2fd97f2d2a98 fwd="103.23.18.14" dyno=web.1 connect=1ms service=338ms status=422 bytes=834 
Aug 14 17:25:31 cobudget-beta-api app/web.1:  Started POST "/api/v1/memberships/upload_review?group_id=255" for 103.23.18.14 at 2016-08-15 00:25:31 +0000 
Aug 14 17:25:31 cobudget-beta-api app/web.1:  Processing by MembershipsController#upload_review as JSON 
Aug 14 17:25:31 cobudget-beta-api app/web.1:    Parameters: {"csv"=>#<ActionDispatch::Http::UploadedFile:0x007f8c3829a920 @tempfile=#<Tempfile:/tmp/RackMultipart20160815-12-g7witx.csv>, @original_filename="report-2016-08-15T1102.csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"csv\"; filename=\"report-2016-08-15T1102.csv\"\r\nContent-Type: application/vnd.ms-excel\r\n">, "group_id"=>"255"} 
Aug 14 17:25:31 cobudget-beta-api app/web.1:  Can't verify CSRF token authenticity 
Aug 14 17:25:31 cobudget-beta-api app/web.1:  Completed 422 Unprocessable Entity in 107ms (Views: 0.4ms | ActiveRecord: 11.0ms) 
```

which means that the csv file is being submitted to the wrong API endpoint -- it should be submitted to `/allocations/upload_review?group_id=255`

i think y'all might be trying to do bulk allocations via csv on the invite_members page -- try http://cobudget.co/#/groups/255/manage_funds

demonstrative GIF

![gif](http://g.recordit.co/gzqKnqqmGl.gif)

**Comment by kiesia** [comment]
My errors are a result of uploading to the allocation endpoint on my dev machine.

**Comment by kiesia** [comment]
@data-doge  You might have already [come across the problem spot](https://github.com/cobudget/cobudget-ui/blob/master/app/components/review-bulk-allocation-page/review-bulk-allocation-page.coffee#L71 )?

**Comment by data-doge** [comment]
@kiesia 

yep certainly agree it needs refactoring, but still -- the huge csv upload works for me locally, and on production

it takes a long time in both cases, but works

currently not sure what to do here

**Comment by kiesia** [comment]
Well if it works then what are we talking about? :smile:

**Comment by data-doge** [comment]
you're getting those 401s tho :/

**Comment by kiesia** [comment]
Ah forget the 401s, that turns out to be an issue with my dev environment. Running node simply as `node .` fixed the issue.

**Comment by kiesia** [comment]
[PR to resolve capitalised emails](https://github.com/cobudget/cobudget-ui/pull/323/files)

**Comment by gardner** [comment]
Charley Davenport reported this via slack: 

> Hi - I’ve run into a problem with a .csv file upload to update funds for Foundation. I used to be able to include multiple line items that included the same email consecutively. like:
> 
> 7.62 team@domain.co.nz
> 6.56 team@domain.co.nz
> 
> But now when I upload it’s giving me the error that I have duplicate email addresses. I’ll resolve this now by simply combining the amounts from multiple lines for the same address into a single line, but  I didn’t have to used to do this, and it was nice to not having to worry about multiple lines with different amounts for the same account. Thanks!

**Comment by data-doge** [comment]
thx @gardner for the notification -- i'm going to it into a separate issue, and close this one.

as far as i can see, with respect to the original issue raised, there's no bug here -- only expected behavior
