### ISSUE TITLE
Make sure that `gem install redcarpet -v '3.4.0'` succeeds before bundling.

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget-api#177]
got an email from @grimmraper

> Hello,
>
> I made a cobudget-ui installation script now I am suffering with the cobudget-api installation script.
When i run the command: bundle install I get this error:
>
> ```
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
>
> current directory:
> /home/adam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redcarpet-3.4.0/ext/redcarpet
> /home/adam/.rbenv/versions/2.4.0/bin/ruby -r ./siteconf20170721-2564-rp3xba.rb
> extconf.rb
> creating Makefile
>
> current directory:
> /home/adam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redcarpet-3.4.0/ext/redcarpet
> make "DESTDIR=" clean
>
> current directory:
> /home/adam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redcarpet-3.4.0/ext/redcarpet
> make "DESTDIR="
> compiling autolink.c
> compiling buffer.c
> buffer.c: In function ‘bufcstr’:
> buffer.c:111:45: warning: passing argument 1 of ‘bufgrow’ discards ‘const’
> qualifier from pointer target type [-Wdiscarded-qualifiers]
>  if (buf->size + 1 <= buf->asize || bufgrow(buf, buf->size + 1) == BUF_OK) {
>                                             ^
> buffer.c:60:1: note: expected ‘struct buf *’ but argument is of type ‘const
> struct buf *’
> bufgrow(struct buf *buf, size_t neosz)
> ^
> buffer.c: At top level:
> cc1: warning: unrecognized command line option ‘-Wno-self-assign’
> cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
> cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
> cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
> compiling houdini_href_e.c
> compiling houdini_html_e.c
> compiling html.c
> compiling html_smartypants.c
> html_smartypants.c: In function ‘squote_len’:
> html_smartypants.c:104:39: warning: initialization discards ‘const’ qualifier
> from pointer target type [-Wdiscarded-qualifiers]
>   static char* single_quote_list[] = { "'", "&#39;", "&#x27;", "&apos;", NULL };
>                                        ^
> html_smartypants.c:104:44: warning: initialization discards ‘const’ qualifier
> from pointer target type [-Wdiscarded-qualifiers]
>   static char* single_quote_list[] = { "'", "&#39;", "&#x27;", "&apos;", NULL };
>                                            ^
> html_smartypants.c:104:53: warning: initialization discards ‘const’ qualifier
> from pointer target type [-Wdiscarded-qualifiers]
>   static char* single_quote_list[] = { "'", "&#39;", "&#x27;", "&apos;", NULL };
>                                                     ^
> html_smartypants.c:104:63: warning: initialization discards ‘const’ qualifier
> from pointer target type [-Wdiscarded-qualifiers]
>   static char* single_quote_list[] = { "'", "&#39;", "&#x27;", "&apos;", NULL };
>                                                                ^
> html_smartypants.c: In function ‘smartypants_squote’:
> html_smartypants.c:149:30: warning: comparison between signed and unsigned
> integer expressions [-Wsign-compare]
> uint8_t next_char = (size > 1+next_squote_len) ? text[1+next_squote_len] :
> 0;
>                               ^
> html_smartypants.c: In function ‘smartypants_cb__amp’:
> html_smartypants.c:250:2: warning: ISO C90 forbids mixed declarations and code
> [-Wdeclaration-after-statement]
>   int len = squote_len(text, size);
>   ^
> html_smartypants.c: At top level:
> cc1: warning: unrecognized command line option ‘-Wno-self-assign’
> cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
> cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
> cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
> compiling markdown.c
>  markdown.c: In function ‘char_link’:
> markdown.c:1045:3: warning: ISO C90 forbids mixed declarations and code
> [-Wdeclaration-after-statement]
>    struct buf id = { 0, 0, 0, 0 };
>    ^
> markdown.c:1085:3: warning: ISO C90 forbids mixed declarations and code
> [-Wdeclaration-after-statement]
>    size_t nb_p = 0;
>    ^
> markdown.c: In function ‘sd_markdown_render’:
> markdown.c:2818:2: warning: ISO C90 forbids mixed declarations and code
> [-Wdeclaration-after-statement]
>   int footnotes_enabled  = md->ext_flags & MKDEXT_FOOTNOTES;
>   ^
> markdown.c:2836:43: warning: passing argument 1 of ‘is_codefence’ discards
> ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
> if (codefences_enabled && (is_codefence(document + beg, doc_size - beg, NULL)
> != 0))
>                                            ^
> markdown.c:1389:1: note: expected ‘uint8_t * {aka unsigned char *}’ but argument
> is of type ‘const uint8_t * {aka const unsigned char *}’
>  is_codefence(uint8_t *data, size_t size, struct buf *syntax)
>  ^
> markdown.c: At top level:
> markdown.c:94:15: warning: ‘char_underline’ declared ‘static’ but never defined
> [-Wunused-function]
> static size_t char_underline(struct buf *ob, struct sd_markdown *rndr, uint8_t
> *data, size_t offset, size_t size);
>                ^
> cc1: warning: unrecognized command line option ‘-Wno-self-assign’
> cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
> cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
> cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
> compiling rc_markdown.c
> rc_markdown.c: In function ‘rb_redcarpet_md_render’:
> rc_markdown.c:138:2: warning: ISO C90 forbids mixed declarations and code
> [-Wdeclaration-after-statement]
>   struct rb_redcarpet_rndr *renderer;
>   ^
> rc_markdown.c: At top level:
> cc1: warning: unrecognized command line option ‘-Wno-self-assign’
> cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
> cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
> cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
> compiling rc_render.c
> rc_render.c: In function ‘rndr_link_attributes’:
> rc_render.c:287:28: warning: variable ‘rndr’ set but not used
> [-Wunused-but-set-variable]
>   struct rb_redcarpet_rndr *rndr;
>                             ^
> rc_render.c: At top level:
> cc1: warning: unrecognized command line option ‘-Wno-self-assign’
> cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
> cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
> cc1: warning: unrecognized command line option ‘-Wno-tautological-compare’
> compiling stack.c
> linking shared-object redcarpet.so
> redcarpet.so: final close failed: Invalid operation
> collect2: error: ld returned 1 exit status
> Makefile:257: recipe for target 'redcarpet.so' failed
> make: *** [redcarpet.so] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in
> /home/adam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/redcarpet-3.4.0 for
> inspection.
> Results logged to
> /home/adam/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/redcarpet-> 3.4.0/gem_make.out
>
> An error occurred while installing redcarpet (3.4.0), and Bundler
> cannot continue.
> Make sure that `gem install redcarpet -v '3.4.0'` succeeds before bundling.
>
> In Gemfile:
>   redcarpet
> ```
>
> I tried installing redcarpet with different versions of ruby, with different ruby installing methods, with  different versions of red carpet, nothing has worked yet. If you could give me some tips I would appreciate it.
>
> Best regards,
> Adam Hegyaljai

**Comment by chime-mu** [comment]
This is a known problem compiling red carpet on certain platforms. Please see https://github.com/vmg/redcarpet/issues/523

Hope this helps :)
