### ISSUE TITLE
POST /memberships

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/cobudget-api#57]
POST /memberships

{
  memberships: [{
    group_id: 43,    
    user: {
      email: "jon.lemmon@enspiral.com"
    },
  }, {
    group_id: 43,
    user: {
      email: "mikey@coolness.com"
    }
  }]
}

**Comment by derekrazo** [comment]
@ahdinosaur says,

```
{
  memberships: [{
    user: {
      email: "jon.lemmon@enspiral.com"
    },
    group_id: 1
  }, {
    user: {
      email: "mikey@coolness.com"
    }
  }]
}
```
