### ISSUE TITLE
Enabling cobudget test & dev

### ISSUE THREAD

**Issue by faddat** [cobudget/cobudget-api#70]
Hey guys,

We'd really like to use cobudget internally at MetaDev, and we'd definitley hack on it with you, too.  So:

1) Any chance that we could pay enspiral or an individual on the team directly so that we could get cobudget up and running on a machine behind our firewall (Or could just be a GCE instance, the point really is the tutorial).  $100?  Less?  More?
2) Any additional setup documentation, etc that you can provide would be awesome.  
Thank you!!!!
-Jake

**Comment by derekrazo** [comment]
Hi Jake!

To give you a bit of context, we are currently in between alpha and beta. This means we've run Cobudget in a bunch of groups, learned heaps and now have a bit of funding, time and team for building out the beta of the app over the next while. 

Hence, we haven't created any documentation on self-hosting (as the product is changing too fast in design stages now to warrant it).

This might make it hard for us to hack on it together in the short term.

All that being said, I'd be really keen to set up a time to chat with you to discuss your use case and make sure that what we're building next is going to serve. Could you reach out to me at derek@enspiral.com ? 

If we can chat, we could also discuss setting you up with the alpha version of the software as well for the time being. 

Hope all that is clear! Thanks for the interest and enthusiasm :)
