### ISSUE TITLE
Story : Admin can notify contributors at round milestones.

### ISSUE THREAD

**Issue by derekrazo** [cobudget/cobudget-api#71]
__As an Admin, I want to be able to notify people in my group at key points in the funding round cycle, 
So that I can get as much engagement as possible.__

Simulates a "draft" and "publish" functionality. UI will be a button on the round (next to the edit button) which lets the app know to publish a stream of emails according to the date settings configured in that round. Should also indicate when something is "published" or "draft" - with a tag.

If round has been set to let people propose buckets - the proposal reminder goes out, otherwise, round simply sends out a funding email once it has started.

### Need to have email milestones

- Round published - "come propose buckets" - includes link to published round's buckets page.
- Round funding started - "come fund things" - includes link to published round's buckets page and how much money the person has

### Nice to have

- Round is about to finish - you've got $X and X days (1 day)
- Rounds is finished, here's the results

**Comment by derekrazo** [comment]
related to https://github.com/open-app/cobudget/issues/73

**Comment by derekrazo** [comment]
@euglazer from @alannallama - the round funding started email should only go out to contributors with money in that round. We're putting this in the "nice to have" box though, so for now it can go out to everyone.

Also @alannallama suggested that the round finished email should be a need to have. Basically just a text list of all the buckets proposed and how much they were funded.

**Comment by derekrazo** [comment]
@alannallama - could you post emails to be sent out here? <3

**Comment by alannallama** [comment]
[Round published] 

Subject: 
Propose Projects for Funding in Cobudget

Body: 
Do you have an idea for a project you would like funded through Cobudget? The next round of funding for [XYZ group] will be starting soon. Propose a project now! 

Cobudget is a collaborative process where groups decide how to spend money together. If you're getting this email, it means you are invited to request project funding from your group. When the funding round begins, people with money available will check out the proposed projects and decide where to spend their part of the group's funds.


[Funding started]

Subject: You have $XXX - Fund projects now in Cobudget!

You have $XXX to spend in the current funding round for [XYZ group]. Check out the proposed projects, and decide what you want to fund.

Cobudget is a collaborative process where groups decide how to spend money together. As a funder, it's up to you to chose the best use of your part of the group's budget, by funding the proposed projects you want to support.

[list proposed project titles in the current round]

Jump into Cobudget now to see more project details, and make your funding decisions.

@euglazer

**Comment by derekrazo** [comment]
This is cool! Reading the emails is a nice way to understand what you're
thinking.

Would love to hear more about "round milestones" and for what other
occasions they might be useful.

**Comment by data-doge** [comment]
@derekrazo 

this is suuuuper old haha

**Comment by data-doge** [comment]
i'm just doin an issue closin spree rn
