### ISSUE TITLE
Default passwords should be more prominent

### ISSUE THREAD

**Issue by Ozzadar** [cobudget/cobudget-api#76]
Just for a dev experience side of things, you should shit things out like the default usernames and passwords generated in bold and sparkles.

generated admin account email: 'admin@example.com', password: 'password'
generated user account email: 'user@example.com', password: 'password'

**Comment by ahdinosaur** [comment]
hey @Ozzadar, great suggestion. :smile_cat: if you submit a pull request i'd be happy to merge it in, relevant code is [here](https://github.com/cobudget/cobudget-api/blob/master/db/seeds.rb).

**Comment by Ozzadar** [comment]
I was going through your beta branch and it seems that on db creation it gets dumped to the console log. Maybe just stick Default accounts: admin@example.com... in your README.md just to make it easier on us poor devs ;)
