### ISSUE TITLE
[beta] email notifications from comments on same bucket have different subjects

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget-api#86]
which leads to

![snapshot5](https://cloud.githubusercontent.com/assets/719605/9831085/d712c83e-599c-11e5-8dd8-78b7e7aff8fd.png)

i find this somewhere between confusing and annoying. :cactus:

**Comment by data-doge** [comment]
new email notification system will be a trello-style periodic digest -- so this won't be any issue anymore

closing :)
